### PR TITLE
Add encryption support for KitKat

### PR DESCRIPTION
**Pull request by patrickfav**
This PR implements AES/CBC + HMAC (Encrypt-then-MAC) encryption for Kitkat devices which do not support AES/GCM (see #6). It also adds migration support if the device gets updated to a newer version.

Intentionally the user must enable kitkat support manually.

### CODE REVIEW

**Comment by patrickfav** [comment]
@davidmigloz If you have time, please take a look at this PR

**Comment by davidmigloz** [comment]
I'll try to find some time tomorrow to review it. Thanks for the work!

**Comment by patrickfav** [comment]
Hey @davidmigloz I will release 0.6.0 this week; just want to check if you will get a chance to look at the PR :)

**Comment by davidmigloz** [comment]
Hi @patrickfav! Sorry for the delay, I started reviewing it last week but I run out of time. I'll try to review it between tonight and tomorrow.

**Comment by davidmigloz** [comment]
I've finished the review, it looks awesome. I really like the way you've implemented the multi-protocol decryption support. I haven't found anything and you've written quite a lot of tests. So I guess it's good to go! 😄

**Comment by patrickfav** [comment]
Great to hear. I had some offline reviews, so some of the issues maybe already fixed before you reviewed them :)

**Pull request merged**
