### PR TITLE
Code review

### PR DESCRIPTION
**Pull request by davidmigloz**
Some improvements and fixes that I've done while reviewing the code.

### CODE REVIEW

**Comment by patrickfav** [comment]
Thanks David, Ill review it in the next couple of days.

**Comment by davidmigloz** [comment]
Sure, take your time 😄

**Comment by patrickfav** [comment]
Thanks, very honored :) I started to look more into security relevant code in my last project (our code needed to comply with the security guidelines of some major credit card company) and figured that a majority of devs creating security relevant libraries are not really experts in that field (no offense to them of course, everybody starts somewhere), so I created my own. 

But anyways, thank you very much for the compliment!

**Comment by patrickfav** [comment]
Lgtm

**Pull request merged**
